name: ui
description: core - ui
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter
  model:
    path: ../../core/model

dev_dependencies:

  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - '../../../graphics/'