name: signup
description: feature - sign up
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  common:
    path: ../../core/common
  cupertino_icons: ^1.0.2
  designsystem:
    path: ../../core/designsystem
  go_router: ^6.2.0
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true